### ISSUE TITLE
Integrate fontkit.js for WebGL

### ISSUE THREAD

**Issue by bryphe** [revery-ui/reason-fontkit#3]
Currently, the WebGL strategy for this library does not work. We should integrate [`fontkit`](https://github.com/foliojs/fontkit) (which has an API surface very similiar, since it inspired this API surface) -for Web/JSOO compilation

**Comment by jchavarri** [comment]
Hey @bryphe I'd like to help with this. The idea of start playing with revery in the browser is so exciting! 🚀 

As far as I understand, the main tasks would be:

- Write bindings for `fontkit` in jsoo. One thing to keep in mind is that jsoo relies on globals to consume the JS library code from the bindings (more info in https://github.com/ocsigen/js_of_ocaml/issues/718). This means we'd probably need to vendor a pre-compiled, standalone version of `fontkit` in the repo.
- Figure out the conditional build process with this new target. Maybe we could do that in a second step, but I wonder if we could leverage the existing `discover` executable for this? I'm not very familiar with Dune / OCaml native 🙂 

Let me know if this makes sense, and/or if I'm missing anything. Thanks!

**Comment by bryphe** [comment]
Hey @jchavarri ! That would be awesome 💯 

> The idea of start playing with revery in the browser is so exciting! 🚀

Agree 100% - and this is really the last hurdle in the way!

> Write bindings for fontkit in jsoo. One thing to keep in mind is that jsoo relies on globals to consume the JS library code from the bindings (more info in ocsigen/js_of_ocaml#718). This means we'd probably need to vendor a pre-compiled, standalone version of fontkit in the repo.

Definitely - it's great you've done so much legwork on this. I haven't found a good way to handle this, yet. The [reason-gl-matrix](https://github.com/bryphe/reason-gl-matrix) repo hit this too - we need to bring in `gl-matrix-min.js`, so we just brought in the vendored version. It's kind of a bummer because you have to bring in all the dependencies on the `index.html` but I'm not sure of a better way at the moment. (In addition, we have to explicitly bring this in for `revery`, too). At least... it's only a one-time cost.

I like your idea in the thread of automating this - perhaps using `fastpack` to bundle up dependencies. @jordwalke has done work with JSOO and had some ideas on this front, too (having a way to specify JS dependencies that don't get compiled themselves, but just included in the compiled bundle).

At least for now - we could use a pre-compiled, standalone version like you suggested. 👍 

> Figure out the conditional build process with this new target. Maybe we could do that in a second step, but I wonder if we could leverage the existing discover executable for this? I'm not very familiar with Dune / OCaml native 🙂

We might not need to do anything special here, actually. This conditional is handled by dune / JSOO - when we're building native, our FFI points to the C implementation, and when we're building with JSOO, our FFI points to the JS implementation - so in some sense, we get this step for free. We just have to make sure our FFI is consistent between the C/JS sides. There might not be too much extra here, aside from listing our JS stub in the dune file in the `js_of_ocaml` stanza, like we do in `reason-gl-matrix`:
https://github.com/bryphe/reason-gl-matrix/blob/c8176212ca6434a206663f9f435f63534fbc6645/src/dune#L4

One thought I had to streamline this work (since it's non-trivial - both in implementing the FFI and hooking up a vendored fontkit.js) was to split up into two steps:

__Part 1: Implement a stub FFI__

For this first part - the goal would just be to not even worry about loading `fontkit.js`, and just implement a stub version of the API here via JS stubs: https://github.com/bryphe/reason-fontkit/blob/7dca0209d848e8be5df0836cdbb87afec12c054e/src/Fontkit.re#L26

We could implement some very bare-minimal behavior for these:

`fk_new_face(fontName: string, size: int)` - just return an object with 'size' as a property.
`fk_load_glyph(face: fk_face, int)` - return an object with the following properties:
- width: face.size
- height: face.size
- bearingX: 0
- bearingY: 0
- advance: 0
- image: a hardcoded image - we could just a data URI of a single white pixel, like: `data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACwAAAAAAQABAAACAkQBADs=`

`fk_shape(face: fk_face, string)` - we could return an array of `fk_shape` - just `[{ codepoint: 0, cluster: 0 }...]`, where the length of the array is the same as the string passed in.

The end goal would be to render a bunch of white squares where letters should be 😄 But this lets us sketch out the JS-boundary of the FFI and make sure that piece is working as expected. It gives us some confidence that everything is wired up with `revery`.

__Part 2: Incorporate fontkit.js__

With this part, we'd bring in our vendored `fontkit.js`, and actually fill in real values for `fk_face`, `fk_glyph`, and `fk_shape`.  I believe our API maps pretty closely to what is exposed via fontkit.js - so hopefully once we get it loaded it's not too hard to finish wiring it up.

This repo was really helpful for me looking through the fontkit.js API: https://github.com/devongovett/fontkit-demo

Also, one `esy` feature that will be helpful in working on this, since we don't have any example JSOO apps in this repo, would be to use the `link:` functionality of esy - adding a `link:` to `reason-fontkit` from `revery` - this will make it easy to test changes to `reason-fontkit` directly in revery.

Sorry for the wall of text / brain dump, hope that helps give some ideas anyway. Thanks again for your help @jchavarri !

**Comment by jchavarri** [comment]
Woah thanks a lot @bryphe! This is awesome!

> Sorry for the wall of text / brain dump

Please don't be, I love this kind of wall of texts! This is _so_ useful, your links and directions will definitely save me a lot of time and they make the goal much more accessible.

The 2-parts plan makes a lot of sense to me, I will take a stab at part 1 this weekend and report back. Thanks again!

**Comment by bryphe** [comment]
Awesome, really excited about this @jchavarri 💯 

Just to give a demo about how close we are to having native / browser support, I tested the `Bin` image animation demo in both browser and native:
![animation2](https://user-images.githubusercontent.com/13532591/49523623-05577780-f85f-11e8-81a7-073d6e24d8e6.gif)

It's really powerful that all the high-level pieces like animations 'just work' in both native and the browser. The text rendering is the only primitive we're missing. 

Lots of cool possibilities from there... Could have a lightweight way to build apps in the browser (like Expo enables for React-Native), but then be able to produce high-performance platform native binaries, too! 

Or possibly integrate with @thangngoc89 's excellent work on [sketch.sh](https://sketch.sh/) and prototype UIs / create visualizations via Sketch's interactive notebook model.

**Comment by thangngoc89** [comment]
wow. this is so cool. I don't think such thing like this works on sketch (yet) but we can share ideas to make it possible
